import { Service, Client, Appointment, Language } from './types';

export const TRANSLATIONS = {
  hu: {
    welcome: "Üdvözöllek",
    setupTitle: "Kezdő beállítások",
    selectLang: "Válassz nyelvet / Select Language / Selectați limba",
    professionLabel: "Mi a szakmád?",
    hair: "Fodrász",
    nails: "Műkörmös",
    cosmetics: "Kozmetikus",
    specLabel: "Célcsoport?",
    women: "Női",
    men: "Férfi",
    unisex: "Vegyes",
    continue: "Tovább",
    dashboard: "Áttekintés",
    month: "Havi nézet",
    clients: "Vendégek",
    settings: "Beállítások",
    newAppt: "Új Időpont",
    editAppt: "Szerkesztés",
    save: "Mentés",
    delete: "Törlés",
    cancel: "Mégse",
    client: "Vendég",
    service: "Szolgáltatás",
    date: "Dátum",
    time: "Idő",
    notes: "Megjegyzés",
    optional: "(Opcionális)",
    listening: "Hallgatom...",
    tapToSpeak: "Koppints a beszédhez",
    micPermission: "Mikrofon engedély szükséges",
    dayOff: "Szabadság",
    busy: "Megtelt",
    free: "Szabad",
    moderate: "Van hely",
    genMessage: "Üzenet írása",
    analyze: "Elemzés",
    settingsTitle: "Működés",
    businessHours: "Nyitvatartás",
    defaultDuration: "Alapértelmezett idő (perc)",
    start: "Kezdés",
    end: "Vége",
    theme: "Téma",
    dark: "Sötét (Midnight)",
    light: "Világos (Porcelain)",
    wakeWord: "Hangvezérlés (Sync)",
    nextClient: "Következő Vendég",
    todaysStats: "Mai Statisztika",
    revenue: "Bevétel",
    appointments: "Mai Időpontok",
    quickActions: "Gyorsműveletek",
    voiceActive: "Sync Asszisztens Aktív",
    sayLuxe: "Mondd: \"Sync\"",
    serviceDurations: "Szolgáltatások Időtartama",
    minutes: "perc",
    login: "Bejelentkezés",
    register: "Regisztráció",
    email: "Email cím",
    password: "Jelszó",
    name: "Teljes név",
    noAccount: "Nincs még fiókod?",
    hasAccount: "Már van fiókod?",
    loginBtn: "Belépés",
    registerBtn: "Regisztráció",
    forgotPass: "Elfelejtett jelszó?",
    search: "Keresés...",
    addClient: "Új Vendég",
    phone: "Telefonszám",
    noClients: "Nincs még felvett vendég.",
    assistant: "Asszisztens"
  },
  en: {
    welcome: "Welcome",
    setupTitle: "Initial Setup",
    selectLang: "Select Language",
    professionLabel: "Your Profession?",
    hair: "Hairdresser",
    nails: "Nail Tech",
    cosmetics: "Cosmetician",
    specLabel: "Target Audience?",
    women: "Women",
    men: "Men",
    unisex: "Unisex",
    continue: "Continue",
    dashboard: "Dashboard",
    month: "Month View",
    clients: "Clients",
    settings: "Settings",
    newAppt: "New Appointment",
    editAppt: "Edit Appointment",
    save: "Save",
    delete: "Delete",
    cancel: "Cancel",
    client: "Client",
    service: "Service",
    date: "Date",
    time: "Time",
    notes: "Notes",
    optional: "(Optional)",
    listening: "Listening...",
    tapToSpeak: "Tap to speak",
    micPermission: "Microphone permission required",
    dayOff: "Day Off",
    busy: "Busy",
    free: "Free",
    moderate: "Moderate",
    genMessage: "Draft Message",
    analyze: "Analyze",
    settingsTitle: "Operations",
    businessHours: "Business Hours",
    defaultDuration: "Default Duration (min)",
    start: "Start",
    end: "End",
    theme: "Theme",
    dark: "Dark (Midnight)",
    light: "Light (Porcelain)",
    wakeWord: "Voice Control (Sync)",
    nextClient: "Next Client",
    todaysStats: "Today's Stats",
    revenue: "Revenue",
    appointments: "Today's Appointments",
    quickActions: "Quick Actions",
    voiceActive: "Sync Assistant Active",
    sayLuxe: "Say \"Sync\"",
    serviceDurations: "Service Durations",
    minutes: "min",
    login: "Login",
    register: "Register",
    email: "Email Address",
    password: "Password",
    name: "Full Name",
    noAccount: "Don't have an account?",
    hasAccount: "Already have an account?",
    loginBtn: "Login",
    registerBtn: "Sign Up",
    forgotPass: "Forgot Password?",
    search: "Search...",
    addClient: "Add Client",
    phone: "Phone Number",
    noClients: "No clients added yet.",
    assistant: "Assistant"
  },
  ro: {
    welcome: "Bine ați venit",
    setupTitle: "Setări Inițiale",
    selectLang: "Selectați Limba",
    professionLabel: "Profesia ta?",
    hair: "Coafor",
    nails: "Manichiură",
    cosmetics: "Cosmeticiană",
    specLabel: "Public țintă?",
    women: "Femei",
    men: "Bărbați",
    unisex: "Unisex",
    continue: "Continuă",
    dashboard: "Panou",
    month: "Lună",
    clients: "Clienți",
    settings: "Setări",
    newAppt: "Programare Nouă",
    editAppt: "Editare",
    save: "Salvează",
    delete: "Șterge",
    cancel: "Anulează",
    client: "Client",
    service: "Serviciu",
    date: "Dată",
    time: "Oră",
    notes: "Note",
    optional: "(Opțional)",
    listening: "Ascult...",
    tapToSpeak: "Atingeți pentru a vorbi",
    micPermission: "Este necesară permisiunea microfonului",
    dayOff: "Zi Liberă",
    busy: "Ocupat",
    free: "Liber",
    moderate: "Locuri disponibile",
    genMessage: "Generare Mesaj",
    analyze: "Analiză",
    settingsTitle: "Operațiuni",
    businessHours: "Ore de Program",
    defaultDuration: "Durată Implicită (min)",
    start: "Început",
    end: "Sfârșit",
    theme: "Temă",
    dark: "Întunecat",
    light: "Luminos",
    wakeWord: "Control Vocal (Sync)",
    nextClient: "Următorul Client",
    todaysStats: "Statistica Zilei",
    revenue: "Venit",
    appointments: "Programările Zilei",
    quickActions: "Acțiuni Rapide",
    voiceActive: "Asistent Sync Activ",
    sayLuxe: "Spune \"Sync\"",
    serviceDurations: "Durata Serviciilor",
    minutes: "min",
    login: "Autentificare",
    register: "Înregistrare",
    email: "Email",
    password: "Parolă",
    name: "Nume Complet",
    noAccount: "Nu ai cont?",
    hasAccount: "Ai deja cont?",
    loginBtn: "Intră în cont",
    registerBtn: "Înregistrare",
    forgotPass: "Ai uitat parola?",
    search: "Căutare...",
    addClient: "Adaugă Client",
    phone: "Număr de telefon",
    noClients: "Nu există clienți.",
    assistant: "Asistent"
  }
};

// HAIR SERVICES
export const SERVICES_WOMEN: Service[] = [
  { id: 'w1', name: 'Női hajvágás / Women Cut', duration: 60, price: 8500, color: 'border-rose-500 bg-rose-500/20 text-rose-700 dark:text-rose-200' },
  { id: 'w2', name: 'Festés (tő) / Color (Roots)', duration: 90, price: 12000, color: 'border-fuchsia-500 bg-fuchsia-500/20 text-fuchsia-700 dark:text-fuchsia-200' },
  { id: 'w3', name: 'Balayage', duration: 180, price: 25000, color: 'border-amber-500 bg-amber-500/20 text-amber-700 dark:text-amber-200' },
  { id: 'w4', name: 'Szárítás / Blow Dry', duration: 30, price: 4000, color: 'border-emerald-500 bg-emerald-500/20 text-emerald-700 dark:text-emerald-200' },
];

export const SERVICES_MEN: Service[] = [
  { id: 'm1', name: 'Hajvágás / Haircut', duration: 30, price: 5000, color: 'border-blue-500 bg-blue-500/20 text-blue-700 dark:text-blue-200' },
  { id: 'm2', name: 'Szakálligazítás / Beard Trim', duration: 20, price: 3000, color: 'border-cyan-500 bg-cyan-500/20 text-cyan-700 dark:text-cyan-200' },
  { id: 'm3', name: 'Full Service', duration: 60, price: 8000, color: 'border-indigo-500 bg-indigo-500/20 text-indigo-700 dark:text-indigo-200' },
];

// NAIL SERVICES
export const SERVICES_NAILS: Service[] = [
  { id: 'n1', name: 'Gél Lakk / Gel Polish', duration: 60, price: 6000, color: 'border-pink-500 bg-pink-500/20 text-pink-700 dark:text-pink-200' },
  { id: 'n2', name: 'Építés / Extension', duration: 120, price: 10000, color: 'border-purple-500 bg-purple-500/20 text-purple-700 dark:text-purple-200' },
  { id: 'n3', name: 'Pedikűr / Pedicure', duration: 60, price: 7000, color: 'border-teal-500 bg-teal-500/20 text-teal-700 dark:text-teal-200' },
];

// COSMETICS SERVICES
export const SERVICES_COSMETICS: Service[] = [
  { id: 'c1', name: 'Arctisztítás / Facial', duration: 90, price: 15000, color: 'border-emerald-500 bg-emerald-500/20 text-emerald-700 dark:text-emerald-200' },
  { id: 'c2', name: 'Gyantázás / Waxing', duration: 30, price: 4000, color: 'border-orange-500 bg-orange-500/20 text-orange-700 dark:text-orange-200' },
  { id: 'c3', name: 'Szempilla / Lashes', duration: 120, price: 18000, color: 'border-violet-500 bg-violet-500/20 text-violet-700 dark:text-violet-200' },
];

// Start with empty clients as requested
export const MOCK_CLIENTS: Client[] = [];

// Start with empty appointments as requested
export const MOCK_APPOINTMENTS: Appointment[] = [];